# Generated by Django 5.0 on 2025-10-17 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
